# Generated by Django 5.1.5 on 2025-06-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Preço total da reserva', max_digits=10, verbose_name='Preço Total')),
                ('session', models.CharField(help_text='Informações da sessão do filme', max_length=100, verbose_name='Sessão')),
                ('seats', models.TextField(help_text='Assentos reservados (formato JSON ou string)', verbose_name='Assentos')),
                ('movie_id', models.CharField(help_text='ID do filme no The Movie Database', max_length=20, verbose_name='ID do Filme (TMDB)')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Concluída')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Reserva de Ingresso',
                'verbose_name_plural': 'Reservas de Ingressos',
                'db_table': 'ticketReservation',
                'ordering': ['-created_at'],
            },
        ),
    ]
